// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIcK1Foyh1Uikh-fW1BPqJYxAG8j-UVw',
    appId: '1:945533104648:web:fd97be83f29c24ed99d7bd',
    messagingSenderId: '945533104648',
    projectId: 'week-8-data-persistence-2a69f',
    authDomain: 'week-8-data-persistence-2a69f.firebaseapp.com',
    storageBucket: 'week-8-data-persistence-2a69f.appspot.com',
    measurementId: 'G-T1T83XWSP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7G36cOV9Ajf3dS682xFfmVIcXkqdYsVw',
    appId: '1:945533104648:android:cd4bf1fb0d7d600699d7bd',
    messagingSenderId: '945533104648',
    projectId: 'week-8-data-persistence-2a69f',
    storageBucket: 'week-8-data-persistence-2a69f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSX71gAt4rhTwhCciNsoUCh-dF1wTeZl8',
    appId: '1:945533104648:ios:9b4f18c0c32cd18199d7bd',
    messagingSenderId: '945533104648',
    projectId: 'week-8-data-persistence-2a69f',
    storageBucket: 'week-8-data-persistence-2a69f.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSX71gAt4rhTwhCciNsoUCh-dF1wTeZl8',
    appId: '1:945533104648:ios:9b4f18c0c32cd18199d7bd',
    messagingSenderId: '945533104648',
    projectId: 'week-8-data-persistence-2a69f',
    storageBucket: 'week-8-data-persistence-2a69f.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNIcK1Foyh1Uikh-fW1BPqJYxAG8j-UVw',
    appId: '1:945533104648:web:e1bb19452f2880e199d7bd',
    messagingSenderId: '945533104648',
    projectId: 'week-8-data-persistence-2a69f',
    authDomain: 'week-8-data-persistence-2a69f.firebaseapp.com',
    storageBucket: 'week-8-data-persistence-2a69f.appspot.com',
    measurementId: 'G-8ZMQ82QLHW',
  );
}
